# ENG : Triangle, pentagonal, and hexagonal numbers are generated by the following formulae: 
# Triangle 𝑇 𝑛 = 𝑛 ( 𝑛 + 1 ) / 2 1 , 3 , 6 , 10 , 15 , … 
# Pentagonal 𝑃 𝑛 = 𝑛 ( 3 𝑛 − 1 ) / 2 1 , 5 , 12 , 22 , 35 , … 
# Hexagonal 𝐻 𝑛 = 𝑛 ( 2 𝑛 − 1 ) 1 , 6 , 15 , 28 , 45 , … 
# It can be verified that 𝑇 285 = 𝑃 165 = 𝐻 143 = 40755 . Find the next triangle number that is also pentagonal and hexagonal.

# TR : Üçgen, beşgen ve altıgen sayılar aşağıdaki formüllerle oluşturulur: 
# Üçgen 𝑇 𝑛 = 𝑛 ( 𝑛 + 1 ) / 2 1 , 3 , 6 , 10 , 15 , … 
# Beşgen 𝑃 𝑛 = 𝑛 ( 3 𝑛 − 1 ) / 2 1 , 5 , 12 , 22 , 35 , … 
# Altıgen 𝐻 𝑛 = 𝑛 ( 2 𝑛 − 1 ) 1 , 6 , 15 , 28 , 45 , … 
# Doğrulanabilir ki 𝑇 285 = 𝑃 165 = 𝐻 143 = 40755 . Aynı zamanda beşgen ve altıgen olan bir sonraki üçgen sayısını bulun.


def is_triangular(x):
    return ((- 1 + (1 + 8 * x) ** 0.5) / 2).is_integer()

def is_pentagonel(x):
    return ((1 + (1 + 24 * x) ** 0.5) / 6).is_integer()

def is_hexagonal(x):
    return ((1 + (1 + 8 * x) ** 0.5) / 4).is_integer()

n = 144

while True:
    hex_ = n * (2 * n - 1)
    if is_triangular(hex_) and is_pentagonel(hex_):
        print(hex_)
        break
    n += 1
