# ENG : The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7 th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28 . 
# The first ten terms would be: 1 , 3 , 6 , 10 , 15 , 21 , 28 , 36 , 45 , 55 , … 
# Let us list the factors of the first seven triangle numbers: 
# 1 : 1 
# 3 : 1 , 3 
# 6 : 1 , 2 , 3 , 6 
# 10 : 1 , 2 , 5 , 10 
# 15 : 1 , 3 , 5 , 15 
# 21 : 1 , 3 , 7 , 21 
# 28 : 1 , 2 , 4 , 7 , 14 , 28 
# We can see that 28 is the first triangle number to have over five divisors. 
# What is the value of the first triangle number to have over five hundred divisors?

# TR : Üçgen sayı dizisi, doğal sayıların eklenmesiyle oluşturulur. 
# Yani 7. üçgen sayısı 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28 olacaktır. 
# İlk on terim şöyle olacaktır: 1 , 3 , 6 , 10 , 15 , 21 , 28 , 36 , 45 , 55 , … 
# İlk yedi üçgen sayısının çarpanlarını sıralayalım: 
# 1 : 1 
# 3 : 1 , 3 
# 6 : 1 , 2 , 3 , 6 
# 10 : 1 , 2 , 5 , 10 
# 15 : 1 , 3 , 5 , 15 
# 21 : 1 , 3 , 7 , 21 
# 28 : 1 , 2 , 4 , 7 , 14 , 28 Görebiliriz 28, beşten fazla böleni olan ilk üçgen sayısıdır. 
# Beş yüzün üzerinde böleni olan ilk üçgen sayısının değeri nedir?

import math

def number_of_division(x):
    dividing = 1
    for i in range(2, int(math.sqrt(x) + 1)):       
        if x % i == 0:
            dividing += 1
    return dividing * 2


n = 1

while True:
    number = (n * (n + 1)) / 2
    if number_of_division(int(number)) > 500:
        print(int(number))
        break
    n += 1
                    
            
                                   
            
        