# ENG : Consider all integer combinations of 𝑎^𝑏 for 2 ≤ 𝑎 ≤ 5 and 2 ≤ 𝑏 ≤ 5 :
# 2^2 = 4 , 2^3 = 8 , 2^4 = 16 , 2^5 = 32 
# 3^2 = 9 , 3^3 = 27 , 3^4 = 81 , 3^5 = 243 
# 4^2 = 16 , 4^3 = 64 , 4^4 = 256 , 4^5 = 1024 
# 5^2 = 25 , 5^3 = 125 , 5^4 = 625 , 5^5 = 3125
# If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms: 
# 4 , 8 , 9 , 16 , 25 , 27 , 32 , 64 , 81 , 125 , 243 , 256 , 625 , 1024 , 3125. 
# How many distinct terms are in the sequence generated by 𝑎 𝑏 for 2 ≤ 𝑎 ≤ 100 and 2 ≤ 𝑏 ≤ 100 ?

# TR : 2 ≤ 𝑎 ≤ 5 ve 2 ≤ 𝑏 ≤ 5 için 𝑎 𝑏'nin tüm tamsayı kombinasyonlarını düşünün:
# 2^2 = 4 , 2^3 = 8 , 2^4 = 16 , 2^5 = 32 
# 3^2 = 9 , 3^3 = 27 , 3^4 = 81 , 3^5 = 243 
# 4^2 = 16 , 4^3 = 64 , 4^4 = 256 , 4^5 = 1024 
# 5^2 = 25 , 5^3 = 125 , 5^4 = 625 , 5^5 = 3125
# Daha sonra tekrarlar çıkarılarak sayısal sıraya yerleştirilirlerse, 15 farklı terimden oluşan aşağıdaki diziyi elde ederiz: 
# 4 , 8 , 9 , 16 , 25 , 27 , 32 , 64 , 81 , 125 , 243 , 256 , 625 , 1024 , 3125. 
# 2 ≤ 𝑎 ≤ 100 ve 2 ≤ 𝑏 ≤ 100 için 𝑎^𝑏 tarafından oluşturulan dizide kaç farklı terim vardır?

numbers = set()

for a in range(2, 101):
    for b in range(2, 101):
        number = a ** b
        numbers.add(number)
        
print(len(numbers))