# ENG : Pentagonal numbers are generated by the formula, 𝑃 𝑛 = 𝑛 ( 3 𝑛 − 1 ) / 2 . The first ten pentagonal numbers are: 
# 1 , 5 , 12 , 22 , 35 , 51 , 70 , 92 , 117 , 145 , … 
# It can be seen that 𝑃 4 + 𝑃 7 = 22 + 70 = 92 = 𝑃 8 . However, their difference, 70 − 22 = 48 , is not pentagonal. 
# Find the pair of pentagonal numbers, 𝑃 𝑗 and 𝑃 𝑘 , for which their sum and difference are pentagonal and 𝐷 = | 𝑃 𝑘 − 𝑃 𝑗 | is minimised; what is the value of 𝐷 ?
    
# TR : Beşgen sayılar 𝑃 𝑛 = 𝑛 ( 3 𝑛 − 1 ) / 2 formülüyle oluşturulur. İlk on beşgen sayı şunlardır: 
# 1 , 5 , 12 , 22 , 35 , 51 , 70 , 92 , 117 , 145 , … 
# Görüldüğü gibi 𝑃 4 + 𝑃 7 = 22 + 70 = 92 = 𝑃 8 . Ancak aralarındaki fark (70 − 22 = 48) beşgen değildir. 
# Toplamları ve farkları beşgen ve 𝐷 = | olan beşgen sayı çiftini bulun, 𝑃 𝑗 ve 𝑃 𝑘 . 𝑃 𝑘 − 𝑃 𝑗 | en aza indirilir; 𝐷'in değeri nedir?


def pentagonal_number(n):
    return (n * (3 * n - 1)) / 2

def is_pentagonal(x):
    return ((1 + (1 + 24 * x) ** 0.5) / 6).is_integer()

for i in range(1, 5000):
    number1 = pentagonal_number(i)
    for j in range(i - 1, 0, -1):
        number2 = pentagonal_number(j)
        if is_pentagonal(number1 + number2) and is_pentagonal(number1 - number2):
            print(number1 - number2)

