# ENG: Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2 , the first 10 terms will be: 1 , 2 , 3 , 5 , 8 , 13 , 21 , 34 , 55 , 89 , … 
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# TR:Fibonacci dizisindeki her yeni terim, önceki iki terimin eklenmesiyle oluşturulur. 
#1 ve 2'den başlayarak ilk 10 terim şöyle olacaktır: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,… 
#Fibonacci dizisindeki değerleri dört milyonu geçmeyen terimler dikkate alınarak , çift değerli terimlerin toplamını bulun.


fibonacci = list()
fibonacci.append(1)
fibonacci.append(2)

index = 2

while True:
    if fibonacci[index - 1] + fibonacci[index - 2] < 4000000:
        fibonacci.append(fibonacci[index - 1] + fibonacci[index - 2])
        index += 1
    else:
        break

sum = 0
for index in fibonacci:
    if index % 2 == 0:
        sum += index
i = 1
for index in fibonacci:
    print(f'{i}.number: {index}')
    i += 1

print(f'Sum of Fibonacci sequence: {sum}')
print(f'Number of elements of Fibonacci sequence: {len(fibonacci)}')